### ISSUE TITLE
[Bug]: impute package moved from CRAN to biocManager

### ISSUE THREAD

**Issue by epzjlm** [genetics-of-dna-methylation-consortium/godmc_phase2#12]
### Scripts

01-check_data.sh

### What happened?

See https://cran.r-project.org/web/packages/impute/index.html

### R version

4.3.3 (February, 2024)

### Python version

None

**Comment by ejh243** [comment]
I have updated the wiki with this information. No need to change the code as we don't install these packages as part of the pipeline.
