### ISSUE TITLE
[Bug]: 03d- 

### ISSUE THREAD

**Issue by ks164** [genetics-of-dna-methylation-consortium/godmc_phase2#18]
### Scripts

03d-non_genetic_methylation_pcs.sh

### What happened?

script runs through loading chunks and reading rows, halts with the following output:

Identified 1 out of 4 PCs with significant genetic component
Error in dimnames(x)[[2L]] %||% if (do.NULL) NULL else { :
  could not find function "%||%"
Calls: main -> %in% -> colnames -> colnames
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted

### R version

4.3.3 (February, 2024)

### Python version

None

### Relevant log output

```shell
Identified 1 out of 4 PCs with significant genetic component
Error in dimnames(x)[[2L]] %||% if (do.NULL) NULL else { :
  could not find function "%||%"
Calls: main -> %in% -> colnames -> colnames
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
```

**Comment by ZXiaopu** [comment]
Hi,

The issue looks like in your current R %in% function does not work.

Can you try the code below to see if it works.

```
a <- c(1,2,3)
b <- 1
b %in% a
```

**Comment by ks164** [comment]
Thanks!

it evaluates to TRUE in my version of R:

> a <- c(1,2,3)
b <- 1
b %in% a
[1] TRUE
>

**Comment by ZXiaopu** [comment]
Hi,

Another reason might be the inconsistent names between PCs and matrixEQTL output. Can you upload these two scripts to your godmc scripts path and remove the .txt? (github cannot upload .R or .sh extension documents so I manually added .txt).
[genetic_meth_pcs_temp.R.txt](https://github.com/user-attachments/files/16928433/genetic_meth_pcs_temp.R.txt)
[03d-non_genetic_methylation_pcs_temp.sh.txt](https://github.com/user-attachments/files/16928434/03d-non_genetic_methylation_pcs_temp.sh.txt)

And then run
```
sbatch 03d-non_genetic_methylation_pcs_temp.sh 
```

we can check the colnames of matrixEQTL results and PCs.

**Comment by ks164** [comment]
Thanks for forwarding the updated scripts; I have run them, but the .Rdata output just contains an error warning:

"Error in tcrossprod(slice, cvrt) : \"tcrossprod\" is not a BUILTIN function\n"

I found some mention of the tcrossprod function changing to a primitive function recently (e.g. https://stat.ethz.ch/pipermail/r-package-devel/2023q4/009958.html)- could this be helpful in debugging?

I've attached the .Rdata and log files (with the fake .txt extension)

[03d_temp.txt](https://github.com/user-attachments/files/16982716/03d_temp.txt)
[matrixEQTL_res.RData.txt](https://github.com/user-attachments/files/16982717/matrixEQTL_res.RData.txt)

**Comment by ks164** [comment]
Oh, and I forgot to mention- tcrossprod does appear to be builtin in my R version

 grep(pattern = "cross", x = builtins(), value = TRUE)
[1] "tcrossprod" "crossprod"

**Comment by epzjlm** [comment]
reinstall of matrixeqtl solved this
