### ISSUE TITLE
[Code Refactor]: Any other option for `quality_type` in the config file if we use Sanger imputation server?

### ISSUE THREAD

**Issue by SiyiSEA** [genetics-of-dna-methylation-consortium/godmc_phase2#25]
### Contact Details

s.w.wang@exeter.ac.uk

### Path to affected file

```shell
config file.
```

### Type of refactor

Code optimisation, Comment improvement

### Description of required code refactor

Hi,

My data has been imputed by the Sanger Imputation Server which use the SHAPEIT2 + PBWT for phase and imputation.

Due to the output files from Sanger Imputation contain the INFO score, I set the `quality_type = 'minimac'` temporarily.

Any other better suggestion for setting the `quality_type` in the config file, since there is no choice fit the Sanger Imputation?

Thanks.

**Comment by ejh243** [comment]
Searching the code base, this variable isn't actually used? Should we remove it therefore @epzjlm ?

**Comment by epzjlm** [comment]
Yes let's remove it.
