### ISSUE TITLE
[Bug]: 09 - Error in psoriasisNOHLA EWAS

### ISSUE THREAD

**Issue by feichel** [genetics-of-dna-methylation-consortium/godmc_phase2#34]
### Contact Details

fabian.eichelmann@dife.de

### Scripts

09-PRS_EWAS.sh

### What happened?

I encounter an error message related to isva when running EWAS on psoriasisNOHLA. The other PGS worked fine...

### R version

4.3.0 (April, 2023)

### Python version

None

### Relevant log output

```shell
Loading PRS data for PsoriasisNOHLA

Performing EWAS for PsoriasisNOHLA on 1320 individuals and 837405 CpGs
Error in La.svd(V) : error code 1 from Lapack routine 'dgesdd'
Calls: main ... add.surrogate.variables -> isva -> isvaFn -> fastICA -> La.svd
Execution halted
```

**Comment by msolerartigas** [comment]
Hi Fabian,

Thanks for your message!

The error you are getting seems to be related to the Singular Value Decomposition (SVD) function (La.svd) from the LAPACK library. From what I see this error could be related to the methylation matrix that is feed into the analysis and it could also be that the analysis is running out of memory. Given that the analyses for the other PRS, using the exact same matrix have worked, I do not think the issue relates to the matrix. I was wondering whether you may be running the analyses is a computer cluster setting and at that point for some reason there may have been a memory problem. Could you perhaps try to run it again making sure there is enough memory and see what happens?

Many thanks for running these analyses!

María

**Comment by feichel** [comment]
Hi María,

thank you for the suggestion. The memory was not the issue, but I found a workaround for the error. 

I switched out the LAPACK library using the following code on our hpc

```

sudo update-alternatives --config libblas.so.3-x86_64-linux-gnu
There are 2 choices for the alternative libblas.so.3-x86_64-linux-gnu (providing /usr/lib/x86_64-linux-gnu/libblas.so.3).

  Selection    Path                                          Priority   Status
------------------------------------------------------------
  0            /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3   35        auto mode
  1            /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3   35        manual mode
* 2            /usr/lib/x86_64-linux-gnu/blas/libblas.so.3    10        manual mode

Press <enter> to keep the current choice[*], or type selection number:
```

```
sudo update-alternatives --config liblapack.so.3-x86_64-linux-gnu
There are 2 choices for the alternative liblapack.so.3-x86_64-linux-gnu (providing /usr/lib/x86_64-linux-gnu/liblapack.so.3).

  Selection    Path                                             Priority   Status
------------------------------------------------------------
  0            /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3    35        auto mode
  1            /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3    35        manual mode
* 2            /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3   10        manual mode

Press <enter> to keep the current choice[*], or type selection number:
```

**Before**
```
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3 
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3;  LAPACK version 3.7.1
```

**After**
```
sessionInfo()
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
```

Runtime was longer, but it finished without error and the results look ok to me. I suspect that updating our R/Ubuntu versions would have also done the trick, but that was not something I wanted to try yet. I found some background info on LAPACK and how to switch the defaults here: [Link](https://csantill.github.io/RPerformanceWBLAS/)

I addition, I found an error in check_upload.sh (or 09-PRS_EWAS) that mistakenly leads to a failed check. The final check for module 9 in check_upload looks for "script finalised" whereas the logs in 09 print "script finalized" =).

**Comment by epzjlm** [comment]
@hannah-e was this your issue?

**Comment by msolerartigas** [comment]
Hi Hannah,

Many thanks for running the PRS analyses!

I am afraid I am not sure what else we can try for this to work. The error seems to appear in line 109 or 113 of the `resources/methylation/PRS.ewas.meffil.R` script, where we are running the EWAS and it seems related to the surrogate variables calculation. At this point we are running the EWAS three different ways: with no methylation covariates (as main analysis), with methylation covariates and with surrogate variables (as sensitivity analyses). At the moment we are using Independent Surrogate Variable Analysis (`sva=F, isva=T`). We could either try a different approach for the surrogate variable analysis (`sva=T, isva=F`) or just to skip this step altogether (`sva=F, isva=F`). 

Please let me know what you think.

María

**Comment by epzjlm** [comment]
An other option to try is to run it on a different R version.

**Comment by hannah-e** [comment]
@epzjlm Josine,
> An other option to try is to run it on a different R version.
I've tried R 4.4.1 and 4.3.3 with the same result. If there's a version you recommend, please let me know and Ill try it.

@msolerartigas María,
`sva=T, isva=F` runs without error, so I could implement this option as an alternative? If I run with `sva=T, isva=F` then I can just run this for psoriasisNOHLA OR I can use this option for all the EWAS in module 09. Easy to do either so pls let me know what is preferred.

Thanks, Hannah

**Comment by CLVallerga** [comment]
Hi Maria,

I posted an issue (#108) a couple of weeks ago and you redirected me to here. I have tried to increase the memory of my job but that did not solve it. Then I changed the settings of the Independent Surrogate Variable Analysis using  sva=T, isva=F. In this case, the script ran but I got another error now. This is the message I have:

Performing EWAS for ADHD on 637 individuals and 841952 CpGs
Number of significant surrogate variables is:  384
Iteration (out of 5 ):1  2  3  4  5
Generating Q-Q plot
Error in est_lambda(P, method = "median") : no valid measurements
Calls: main -> qqplot_pval -> est_lambda
Execution halted


Do you know what could be the reason for this message? How can I solve it?

Thank you!
Costanza

**Comment by hannah-e** [comment]
Hello @CLVallerga 

I think this is because you need to change the code in the .R script

PRS.ewas.meffil.R
Line 122
qqplot_pval(res$isva, file=paste(qqplot_file,"isvacovs.pdf",sep="."))

There is no object called res$isva if you ran the EWAS with sva.

you need to update to:
qqplot_pval(res$sva, file=paste(qqplot_file,"svacovs.pdf",sep="."))

**Comment by msolerartigas** [comment]
Thanks Hannah!

**Comment by Carla1990** [comment]
Hi @msolerartigas, also me and Cecilia had this type of error, but we solved it changing sva=T and isva=F.

**Comment by msolerartigas** [comment]
Great, thanks for letting me know!

**Comment by Carla1990** [comment]
Just one more thing, we change the name of the qqplots "EPICOR_PRS_..._EWAS_qqplot.svacovs" in "EPICOR_PRS_..._EWAS_qqplot.isvacovs" for the  ./check_upload.sh 09 check and upload.

**Comment by msolerartigas** [comment]
ok, thanks! :)
