### ISSUE TITLE
03g: need finite ylim for plots

### ISSUE THREAD

**Issue by ks164** [genetics-of-dna-methylation-consortium/godmc_phase2#41]
Hi,
I have pulled the latest commit and the same error persists with 03g:

Error in plot.window(...) : need finite 'ylim' values

sorry, I couldn't re-open the original issue

_Originally posted by @ks164 in https://github.com/genetics-of-dna-methylation-consortium/godmc_phase2/issues/36#issuecomment-2389243925_

**Comment by ks164** [comment]
I managed to get the script to run by cloning resources/genetics/plot_gwas.R and modifying lines as follows:

29:     ylim = c(0, round(max(-log10(data), -log10(exp_pvalues), na.rm = TRUE))),
94:    lambda = median(chisq, na.rm = TRUE) / qchisq(0.5,1)
116:  lambda = median(chisq, na.rm = TRUE) / qchisq(0.5,1)

**Comment by SiyiSEA** [comment]
Oh! Thanks Karen.

**Comment by ejh243** [comment]
@SiyiSEA can you implement this and link to a PR? Thanks
