### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by EvansKip1** [genetics-of-dna-methylation-consortium/godmc_phase2#44]
### Contact Details

e.cheruiyot@uq.edu.au

### Scripts

03e-methylation_adjustment2.sh

### What happened?

An error happened when I run 03e at least for the untransformed data set part of this coed, in which no PC remained after running 03d (i.e., 2 out of 2 of the PC had genetic effects such that the "meth_pcs_nongenetic_untransformed.txt" is an IID single column dataframe). I suspect the issue arose from Line36 of "adjust_nongeneticpcs.R".

### How can the bug be reproduced?

run 03e

### R version

4.3.3 (February, 2024)

### Python version

None

### Relevant log output

```shell
Adjusting methylation for meth PCs
Running batch 5 of 150
Reading methylation data...
Data size: 958 individuals and 3060 CpGs.
Error in covs$IID : $ operator is invalid for atomic vectors
Calls: main
Execution halted
```

**Comment by ZXiaopu** [comment]
Hi,

Can you use "git pull" to download the latest version pipeline? This issue should be fixed with the pipeline updated last week.

Thank you

**Comment by ejh243** [comment]
@EvansKip1 Can you confirm if this is fixed now and we can close? 

@ZXiaopu can you link the issue to a PR so we can trace how this was solved?

**Comment by EvansKip1** [comment]
Yes. Fixed. Thanks

**Comment by ZXiaopu** [comment]
> @EvansKip1 Can you confirm if this is fixed now and we can close?
> 
> @ZXiaopu can you link the issue to a PR so we can trace how this was solved?

Done. Thanks
