### ISSUE TITLE
[Bug]: 4a error

### ISSUE THREAD

**Issue by drsora** [genetics-of-dna-methylation-consortium/godmc_phase2#55]
### Contact Details

sonja.rajic@tuni.fi

### Scripts

04a-convert_snp_format.sh

### What happened?

I'm getting this error:
nX=`grep ^X ${bfile}.bim |wc -l`

grep: .bim: No such file or directory

All previous modules ran correctly.

### R version

4.4.0 (April, 2024)

### Python version

None

**Comment by epzjlm** [comment]
Hello,

Could you try on the command line: 

source config
nX=grep ^X ${bfile}.bim |wc -l
echo $nX

**Comment by drsora** [comment]
Hi,

I get this output:

```
bash: ^X: command not found
0
```

**Comment by drsora** [comment]
I managed to run it surrounding it with ``, but the echo $nX returns 1591

**Comment by epzjlm** [comment]
Ah thanks yes we need to update that line to

nX=`grep ^X ${bfile}.bim |wc -l` in the script.

We are not expecting any X coding in the bim file. Do you know where 23 is recoded to X?

We have added a line to 04a. Could you try whether this works?

source config
${plink2} --bfile ${bfile} --make-bed --output-chr 26 --out ${hase_dir_in}
nX=`grep ^X ${bfile}.bim |wc -l`
echo $nX

Thank you.

**Comment by drsora** [comment]
I'm not sure when it happened. I reran 2a just now in case there were new updates since I first ran it.

I also ran 

source config
${plink2} --bfile ${bfile} --make-bed --output-chr 26 --out ${hase_dir_in}
nX=`grep ^X ${bfile}.bim |wc -l`
echo $nX

as you suggested but I'm still getting the following output:

```
867 samples (404 females, 463 males; 867 founders) loaded from
/data/sonja/godmc/processed_data/genetic_data/data.fam.
7668981 variants loaded from
/data/sonja/godmc/processed_data/genetic_data/data.bim.
Note: No phenotype data present.
Writing /data/sonja/godmc/processed_data/hase/hase_in.fam ... done.
Writing /data/sonja/godmc/processed_data/hase/hase_in.bim ... done.
Writing /data/sonja/godmc/processed_data/hase/hase_in.bed ... done.
End time: Fri Oct 25 16:52:02 2024
nX=`grep ^X ${bfile}.bim |wc -l`
echo $nX
1591
```

**Comment by msolerartigas** [comment]
I have also come across this issue, since I had some chrX variants, and got some errors, but after doing some edits to script 4a I managed to run it.

First, I changed line 14 to add ``, as you mentioned previously:
````
nX=`grep ^X ${bfile}.bim | wc -l` 
````
Then, I got the following error:
````
ValueError: invalid combinate of [values_axes] on appending data [name->CHR,cname->CHR,dtype->string360,kind-shape->(1, 100000)] vs current table [name->CHR,cname->CHR,dtype->int64,kind->integer,shape->None]
````
That was because phyton did not find my files formatted by plink changing X to 23 because it was saving them the directory above.
So I fixed it by changing line 17 to add `/data`  at the end:
```
${plink2} --bfile ${bfile} --make-bed --output-chr 26 --out ${hase_dir_in}/data
```

Then, I still had another error:
```
ValueError: There are different data format set(['.bim', '.log', '.fam', '.bed']) in /media/mribases/DATOS1/Satalia_Llonga/GoDMC2/analysis_whole_blood/processed_data/hase/hase_in folder
```
This was because of the log file from plink in the `${hase_dir_in}` directory, so I fixed it by removing it, adding the following to line 18: 
 ```
rm ${hase_dir_in}/data.log
```
After that it ran smoothly.
