### ISSUE TITLE
[Bug]: Install ggpubr

### ISSUE THREAD

**Issue by SunYidan2021** [genetics-of-dna-methylation-consortium/godmc_phase2#56]
### Scripts

00-setup_folders.sh

### What happened?

I cannot install the `quantreg` package. It appears that this issue might be partly due to compatibility problems with the GCC compiler version currently available on our system. The specific error involves undefined symbols, suggesting a deeper issue with the library links or the absence of required components in the GCC setup.
```
Error: package or namespace load failed for ‘quantreg’ in dyn.load(file, DLLpath = DLLpath, ...):
  unable to load shared object '~/GoDMC/R_library/00LOCK-quantreg/00new/quantreg/libs/quantreg.so':
  ~/GoDMC/R_library/00LOCK-quantreg/00new/quantreg/libs/quantreg.so: undefined symbol: _ZGVbN2vv_pow
```
While I can install most of the other required packages, ggpubr remains another package that I cannot install. I would like to ask if I can continue to analysis without `quantreg` package.

### R version

4.2.1 (June, 2022)

### Python version

None

**Comment by epzjlm** [comment]
I think  ggpubr is being used in ./resources/genetics/PRS_qc.R

**Comment by msolerartigas** [comment]
Yes, ggpubr is used in PRS_qc.R. I could change the code to use the package gridExtra instead, would that be a better option?
Thanks!

**Comment by SunYidan2021** [comment]
> Yes, ggpubr is used in PRS_qc.R. I could change the code to use the package gridExtra instead, would that be a better option? Thanks!

I solved it! Thank you!
