### ISSUE TITLE
[Bug]: 11c-check_compress_data.sh qqplot outputs are .jpeg not .png

### ISSUE THREAD

**Issue by hannah-e** [genetics-of-dna-methylation-consortium/godmc_phase2#59]
### Contact Details

hannah.elliott@bristol.ac.uk

### Scripts

11c-check_compress_data.sh

### What happened?

Running 11c-check_compress_data.sh returns an error "Problem: QQ plots of age accelerations are absent"

Line 79 is looking for .png results files:
QQplot=$(find ${section_10_dir} -type f -name "*_qqplot.png" | wc -l)

QQ plot outputs for section 10a are .jpeg files.

Suggested fix: Update Line 79 of 11c:
QQplot=$(find ${section_10_dir} -type f -name "*_qqplot.jpeg" | wc -l)

### How can the bug be reproduced?

run script 11c

### R version

4.3.3 (February, 2024)

### Python version

None

### Relevant log output

```shell
GoDMC2 version 1.0.0
Commit: adb482ef5c9153c2ff42e362b9f8cdfc992396c1
Commit date: 2024-10-21 17:55:15 +0100
Current time: Sat Oct 26 21:34:51 BST 2024

Please ensure your scripts are up to date.
If in doubt, run 'git pull'



Checking log files for 03a-methylation_variables.sh
03a-methylation_variables.sh completed successfully.
Checking results files for 03a-methylation_variables.sh
Plot of age predictions is present
Plot of correleation on age predictions is present
Statistic table of age predictions is present
Correleation table of age predictions is present
Section 03a has been successfully completed!

Checking log files for 10a-gwas_aar.sh
10a-gwas_aar.sh completed successfully.
Checking results files for 10a-gwas_aar.sh
The GWAS results are present
Manhattan plots of age accelerations are present
Problem: QQ plots of age accelerations are absent
```

**Comment by SiyiSEA** [comment]
the pull request  #67 has done.
