### ISSUE TITLE
install error message: EpiDISH requires R.4.1 or greater

### ISSUE THREAD

**Issue by ks164** [genetics-of-dna-methylation-consortium/godmc_phase2#6]
### Contact Details

ks164@duke.edu

### Which wiki documentation

System requirements

### Fault type

Incorrect/outdated information given

### Please describe the fault in details

Did not install under R.4.0.2
successfully installed under R.4.4.1

**Comment by epzjlm** [comment]
Thank you for submitting this issue. We have now updated this on the wiki. I was able to install EpiDISH under R4.1.
