### ISSUE TITLE
[Bug]: 9 stops at AD EWAS

### ISSUE THREAD

**Issue by drsora** [genetics-of-dna-methylation-consortium/godmc_phase2#61]
### Contact Details

sonja.rajic@tuni.fi

### Scripts

09-PRS_EWAS.sh

### What happened?

The script ran smoothly until it got to EWAS for AD. Error is shown below. 

### R version

4.4.0 (April, 2024)

### Python version

None

### Relevant log output

```shell
Running EWAS for AD

Warning messages:
1: multiple methods tables found for ‘sort’
2: multiple methods tables found for ‘sort’
Loading non genetic methylation PCs
No covariates file present for AD
Loading methylation data
Loading PRS data for AD

Performing EWAS for AD on 882 individuals and 768853 CpGs
Error in La.svd(V) : error code 1 from Lapack routine 'dgesdd'
Calls: main ... add.surrogate.variables -> isva -> isvaFn -> fastICA -> La.svd
Execution halted
```

**Comment by msolerartigas** [comment]
Hi Sonja,

Thanks for your message!

There is an issue that is now closed ([Bug]: 09 - Error in psoriasisNOHLA EWAS #34) that reports the same error and a posible solution. Can you have a look and see whether that works for you?

Thank you!
María

**Comment by ejh243** [comment]
@drsora based on conversation today we can close this issue?
