### ISSUE TITLE
[Bug]: 03b-methylation_adjustment1.sh: two RData data missing

### ISSUE THREAD

**Issue by luanjianan** [genetics-of-dna-methylation-consortium/godmc_phase2#82]
### Contact Details

jianan.luan@mrc-epid.cam.ac.uk

### Scripts

03b-methylation_adjustment1.sh

### What happened?

./03b-methylation_adjustment1.sh ${meth_chunks}
does not procuce RData for chunk 1 and 2, while there are no error messages in their log files, with "Successfully adjusting covariates" in last line. The other 98 meth_chunks (3-100) were successfull.

### R version

4.3.1 (June, 2023)

### Python version

Older than 3.4

### Relevant log output

```shell
GoDMC2 version 1.0.0
Commit: ebfbd97f2db249e9980fd7143784ce52d8002031
Commit date: 2024-11-18 11:19:56 +0000
Current time: Sun Nov 24 11:29:43 GMT 2024

Please ensure your scripts are up to date.
If in doubt, run 'git pull'


Running batch 1 of 100
You have specified that the data is not family data. Adjusting only for covariates.
Generating normally transformed residuals
Reading methylation data...
Data size: 1024 individuals and 4792 CpGs.
Probe 1 of 4390
Probe 2 of 4390
......omit.....................
Probe 4390 of 4390
Replace 11378 missing values with rowmeans
Probe 1 of 4390
Probe 2 of 4390
......omit.....................
Probe 4390 of 4390
Replace 8772 missing values with rowmeans
Probe 1 of 402
Probe 2 of 402
......omit.....................
Probe 402 of 402
Replace 144 missing values with rowmeans
Generating untransformed residuals
Reading methylation data...
Data size: 1024 individuals and 4792 CpGs.
Probe 1 of 4390
Probe 2 of 4390
......omit.....................
Probe 4390 of 4390
Replace 11378 missing values with rowmeans
Probe 1 of 4390
Probe 2 of 4390
......omit.....................
Probe 4390 of 4390
Replace 8772 missing values with rowmeans
Probe 1 of 402
Probe 2 of 402
......omit.....................
Probe 402 of 402
Replace 144 missing values with rowmeans
Successfully adjusting covariates
```

**Comment by ZXiaopu** [comment]
Hi,

The log file looks well to me. In this step, we divided the whole DNAm dataset into 100 subsets. If any DNAm subsets only have chrX or chrY CpGs, (un)transformed_methylation_adjusted.[0-9]*Rdata (including autosomal CpGs) won’t be generated but (un)transformed_methylation_adjusted.Male.chrX.[0-9]*Rdata (including sex chr CpGs) will be generated. This situation is more likely to occur with 450K data—fewer CpGs in each DNAm subset lead to a higher probability of all-sex chr CpGs.
 
The log file told me that the first DNAm subset contains 4390 chrX CpGs, 402 chrY CpGs, and no autosomal CpGs. Therefore, (un)transformed_methylation_adjusted.1.Rdata is not generated but (un)transformed_methylation_adjusted.Female.chrX.1.Rdata, (un)transformed_methylation_adjusted.Male.chrX.1.Rdata, (un)transformed_methylation_adjusted.Male.chrY.1.Rdata should be available.
 
We also had a check step in the next step when aggregating 03b results to ensure covariates are adjusted for all CpGs. Please proceed with the aggregation step and check the output.

Thanks!
