### ISSUE TITLE
[Bug]: script ./03d-non_genetic_methylation_pcs.sh failed

### ISSUE THREAD

**Issue by luanjianan** [genetics-of-dna-methylation-consortium/godmc_phase2#83]
### Contact Details

jianan.luan@mrc-epid.cam.ac.uk

### Scripts

03d-non_genetic_methylation_pcs.sh

### What happened?

the script ./03d-non_genetic_methylation_pcs.sh failed with an error message "Error in if (length(l) == ncol(pc)) { : argument is of length zero", see details in log output section.  
File ./processed_data/methylation_data/meth_pcs_nongenetic_transformed.txt was created, but there is no file ./processed_data/methylation_data/meth_pcs_nongenetic_untransformed.txt.

### How can the bug be reproduced?

In the Normalised methylation data - Normalise QC'd samples step (https://github.com/perishky/meffil/wiki/Functional-normalization), my estimate of the number of principal components is 6 and so I set "pc <- 6".  while, I did not change the default settings for pc in the config file in which the settings are:
# PCA paramaters (see 02).
n_pcs="20"
pca_sd="7"
# Methylation PCs (see 03c and d).
n_meth_pcs="20"
meth_pc_cutoff="0.8"
meth_pc_threshold="1e-7"

### R version

4.3.1 (June, 2023)

### Python version

Older than 3.4

### Relevant log output

```shell
GoDMC2 version 1.0.0
Commit: ebfbd97f2db249e9980fd7143784ce52d8002031
Commit date: 2024-11-18 11:19:56 +0000
Current time: Mon Nov 25 15:04:41 GMT 2024

Please ensure your scripts are up to date.
If in doubt, run 'git pull'


Performing genetic analysis of methylation PCs of transformed data by MatrixEQTL
Loading genetic data
Rows read: 2 done.
Performing analysis using 12 threads
.......omit..............................
100.00% done, 0 eQTLs
No significant associations were found.

Identified 0 out of 2 PCs with significant genetic component
Keeping 2 non-genetic PCs.

Performing genetic analysis of methylation PCs of untransformed data by MatrixEQTL
Loading genetic data
Rows read: 1 done.
Performing analysis using 12 threads
.......omit..............................
100.00% done, 0 eQTLs
No significant associations were found.

Identified 1 out of  PCs with significant genetic component
Error in if (length(l) == ncol(pc)) { : argument is of length zero
Calls: main
Execution halted
```

**Comment by ZXiaopu** [comment]
Hi,

The log file says the issue results from the processed_data/methylation_data/meth_pcs_untransformed.RData

Could you please
1/ Confirm this file is available. `ls ${home_directory}/processed_data/methylation_data/meth_pcs_untransformed.RData`
2/ Check if the 03c script runs successfully and share the log file with me. `${section_03_dir}/logs_c/log.txt`

Thanks

**Comment by luanjianan** [comment]
Hi Xiaopu,

I just want to know if the script has been modified? If yes, from which script should I rerun it?
Thanks
Jianan

**Comment by ZXiaopu** [comment]
Hi Jianan,

Sorry for the delay.

My working server is still broken and won't be fixed until Jan 2025. I have to generate a simulated dataset to modify the scripts which led to some delay. I have sent updated scripts to other GoDMC developer to test and hope it works for the one PC issue.

The script is expected to be released before Thursday.

Thanks,
Xiaopu

**Comment by luanjianan** [comment]
Hi Xiaopu, thank you very much for your message and for your time and efforts!

**Comment by ZXiaopu** [comment]
Hi Jianan,

The bug has been fixed in main branch. Can you run `git pull` to download the modified scripts and rerun from 03c?

**Comment by luanjianan** [comment]
Thank you Xiaopu.  Following your instruction, I updated the scripts and re-ran it from 03c.  This time there is no error message from 03d. However, the file ./processed_data/methylation_data/meth_pcs_nongenetic_untransformed.txt does not exist (not created), and there is a comment at the end of the log file:

   Identified 1 out of 1 PCs with significant genetic component
   It appears that all the PCs have a genetic component
   This is a little worrying because it suggests family effects or stratification
   Please check that 03b is adjusting for these factors
   You could also try increasing the 'n_meth_pcs and/or meth_pc_cutoff' value in the config file.

   Successfully generating non-genetic methylation PCs

Our data is an unrelated cohort data, and the covariates I used are: Age_numeric, Sex_factor, plate_factor, and Slide_factor.  The parameters n_meth_pcs and meth_pc_cutoff are 20 and 0.8, respectively, in the config file.  

I attached the log files of 03c and 03d.  Please advice me what I should do next. 
[log-03c.txt](https://github.com/user-attachments/files/18111752/log-03c.txt)
[log_03d.txt](https://github.com/user-attachments/files/18111753/log_03d.txt)

Thank you very much.

**Comment by ZXiaopu** [comment]
Hi Jianan,

It's good to know it works!

Your result is expected. Here is how it works - 
1/ The 1 PC of untransfromed methylation dataset is a genetic PC which it won't be adjusted, therefore no ./processed_data/methylation_data/meth_pcs_nongenetic_untransformed.txt will be generated. 
2/ 03e (which adjust non-genetic PC) will be automatically skipped for untransformed methylation data but still work on transformed methylation data.

Please proceed with 03e.

**Comment by ZXiaopu** [comment]
Hi Jianan,

Thanks for pointing out this issue.

It has been solved and tested by other members. Please use the updated scripts to proceed.

Thanks,
Xiaopu

**Comment by luanjianan** [comment]
Thank you Xiaopu.  Sorry, I tried "git pull" but no new update is available.

**Comment by ZXiaopu** [comment]
Sorry my bad! Can you try now? It should be updated

**Comment by luanjianan** [comment]
Great, thank you very much for your help.  03 results have been updated.
Cheers

**Comment by luanjianan** [comment]
Thank you very much for your help.  03 results have been uploaded.
Cheers!
