### ISSUE TITLE
Methylation data NAs

### ISSUE THREAD

**Issue by drsora** [genetics-of-dna-methylation-consortium/godmc_phase2#84]
### Contact Details

sonja.rajic@tuni.fi

### Scripts

01-check_data.sh

### What happened?

Because my methylation data uses both epic v1 and v2, it had to be preprocessed with sesame, leaving many, many NAs. If I remove them all, I'm left with 352732 out of 721451 probes. 
What's the procedure with this?

There is a vague possibility to repreprocess the data (maybe with meffil?) but it would be very ambitious an idea to get it done by the end of the year ie by the cut-off date. 

### R version

4.4.0 (April, 2024)

### Python version

None

**Comment by ejh243** [comment]
What is the proportion of samples with v1 and v2?

**Comment by epzjlm** [comment]
meffil can do this:

qc.objects <- meffil.qc(samplesheet, featureset="epic:epic2", verbose=T)

**Comment by drsora** [comment]
@ejh243 431 with v1 (it's in 2 batches) and 912 with v2
@epzjlm I managed to do it, though I see some clustering in the PC1 plot, probably due to the arrays. I'd then add an array column to the covariates file. I'm just wondering, if we do it like this, what do I put in our config file, where it asks for the array, does it accept epic:epic2?

**Comment by epzjlm** [comment]
is the clustering on the control probes or on the methylation probes?

**Comment by drsora** [comment]
methylation

**Comment by epzjlm** [comment]
I just checked the meffil.list.featuresets() and meffil.get.features() do accept epic:epic2 and these are the only functions that  use the methylation variable from the config file I think so you can use epic:epic2 in the config file.

**Comment by drsora** [comment]
I repreprocessed the data with meffil and now it works like a charm. Thanks for the help!
