### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xuz1** [genetics-of-dna-methylation-consortium/godmc_phase2#9]
### Scripts

01-check_data.sh

### What happened?

config file require 
sftp_username=""
sftp_username_nc866=""
and
key=""
how to get these information

### R version

4.4.0 (April, 2024)

### Python version

None

**Comment by epzjlm** [comment]
Hello,

You will get this information after registration. You can find more instructions in the "Upload of results for meta-analysis section" [here](https://github.com/genetics-of-dna-methylation-consortium/godmc_phase2/wiki/Install-and-set-up).

Thank you.
